language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build   --verbose
  - cargo test    --verbose --release
  - cargo rustdoc --verbose -- --html-in-header rustdoc-include-katex-header.html
matrix:
  fast_failures: true
  include:
    - rust: stable
      env: FMT=1
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --check
    - rust: nightly
      env: CLIPPY=1
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy
